name: Pre-Shared-Infrastructure Deployment Pipeline

trigger:
  - master

pool:
  vmImage: ubuntu-22.04

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: resourceGroup
    value: jenkins-state-${{ lower(parameters.environment) }}
  - name: storageAccount
    value: sdsstate${{ lower(parameters.environment) }}
  - name: container
    value: tfstate-${{ lower(parameters.environment) }}
  - name: serviceConnection
    value: DTS-SHAREDSERVICES-${{ upper(parameters.environment) }}
  # - name: terraformInitSubscription
  #   value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  # - group: pre-azure-devops-agent

parameters:

  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

  - name: environment
    displayName: Environment
    type: string
    default: "Dev"
    values:
      - Sbox
      - Dev
      - Demo
      - Test
      - Stg
      - Prod

steps:

  - task: PowerShell@2
    displayName: Set terraform version env variable
    inputs:
      targetType: 'inline'
      script: |
        $tfVersion = Get-Content "$(System.DefaultWorkingDirectory)/.terraform-version" -Raw
        Write-Host "##vso[task.setvariable variable=tfVersion]$tfVersion"

  - task: AzureCLI@2
    displayName: Azure CLI
    inputs:
      azureSubscription: $(ServiceConnection)
      scriptType: 'bash'
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az account show
        az account list
        az account get-access-token

  - task: TerraformInstaller@0
    displayName: 'Install terraform $(tfVersion)'
    inputs:
      terraformVersion: $(tfVersion)

  - task: AzureCLI@2
    name: spoutput
    inputs:
      azureSubscription: $(ServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "##vso[task.setvariable variable=spId]$servicePrincipalId"
        echo "##vso[task.setvariable variable=spKey]$servicePrincipalKey"
        echo "##vso[task.setvariable variable=tenantId]$tenantId"
      addSpnToEnvironment: true
      failOnStandardError: true

  - task: TerraformCLI@0
    displayName: Terraform init
    inputs:
      command: init
      #commandOptions: '-lock=false' # don't lock on PRs / validate phase
      terraformVersion: $(tfVersion)
      workingDirectory: $(System.DefaultWorkingDirectory)
      backendType: 'azurerm'
      backendServiceArm: $(ServiceConnection)
      backendAzureRmResourceGroupName: ${{ variables.resourceGroup }}
      backendAzureRmStorageAccountName: ${{ variables.storageAccount }}
      backendAzureRmContainerName: ${{ variables.container }}
      backendAzureRmKey: 'pre/${{ lower(parameters.environment) }}/terraform.tfstate'

  - task: TerraformCLI@0
    displayName: Terraform validate
    inputs:
      command: 'validate'
      workingDirectory: $(System.DefaultWorkingDirectory)

  - task: TerraformCLI@0
    displayName: Terraform plan
    inputs:
      command: plan
      runAzLogin: true
      terraformVersion: $(tfVersion)
      commandOptions: '-out=tfplan -var-file=${{ lower(parameters.environment) }}.tfvars -lock=false'
      workingDirectory: $(System.DefaultWorkingDirectory)
      environmentServiceNameAzureRM: $(ServiceConnection)


# steps:
#
#   - task: TerraformInstaller@0
#     displayName: 'install terraform $(tfVersion)'
#     inputs:
#       terraformVersion: $(tfVersion)

#   - task: TerraformCLI@0
#     displayName: Terraform init
#     inputs:
#       command: init
#       #commandOptions: '-lock=false' # don't lock on PRs / validate phase
#       terraformVersion: $(tfVersion)
#       workingDirectory: $(System.DefaultWorkingDirectory)
#       backendType: 'azurerm'
#       backendServiceArm: $(ServiceConnection)
#       backendAzureRmResourceGroupName: ${{ variables.resourceGroup }}
#       backendAzureRmStorageAccountName: ${{ variables.storageAccount }}
#       backendAzureRmContainerName: ${{ variables.container }}
#       backendAzureRmKey: 'pre/${{ lower(parameters.environment) }}/terraform.tfstate'

#   - task: TerraformCLI@0
#     displayName: Terraform validate
#     inputs:
#       command: 'validate'
#       workingDirectory: $(System.DefaultWorkingDirectory)

#   - task: TerraformCLI@0
#     displayName: Terraform plan
#     inputs:
#       command: plan
#       terraformVersion: $(tfVersion)
#       commandOptions: '-out=tfplan -var-file=${{ lower(parameters.environment) }}.tfvars -lock=false'
#       workingDirectory: $(System.DefaultWorkingDirectory)
#       environmentServiceNameAzureRM: $(ServiceConnection)


  # - task: TerraformCLI@0
  #   displayName: Terraform apply
  #   condition: and(succeeded(), eq('${{ parameters.Action }}', 'apply'))
  #   inputs:
  #     command: apply
  #     terraformVersion: $(tfVersion)
  #     commandOptions: '--auto-approve tfplan'
  #     workingDirectory: $(System.DefaultWorkingDirectory)
  #     environmentServiceNameAzureRM: 'devops-test-service-connection'
