name: Pre-Shared-Infrastructure Deployment Pipeline

trigger:
  - master

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: azure-devops-templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

variables:
  - name: resourceGroup
    value: jenkins-state-${{ lower(parameters.environment) }}
  - name: storageAccount
    value: sdsstate${{ lower(parameters.environment) }}
  - name: container
    value: tfstate-${{ lower(parameters.environment) }}
  - name: serviceConnection
    value: DTS-SHAREDSERVICES-${{ upper(parameters.environment) }}

parameters:

  - name: action
    type: string
    default: plan
    values:
      - plan
      - apply

  - name: environment
    displayName: Environment
    type: string
    default: "Dev"
    values:
      - Sbox
      - Dev
      - Demo
      - Test
      - Stg
      - Prod
  
steps:

  # - task: InstallSSHKey@0
  #   displayName: 'Install SSH Key'
  #   inputs:
  #     knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
  #     sshKeySecureFile: 'pre_github_id_rsa'
  #     # hostName: 'github.com'
  #     # sshPublicKey: 'not required'
  #     # sshKeySecureFile: 'jenkins_ssh_pk'

  - task: PowerShell@2
    displayName: Set terraform version env variable
    inputs:
      targetType: 'inline'
      script: |
        $tfVersion = Get-Content "$(System.DefaultWorkingDirectory)/.terraform-version" -Raw
        Write-Host "##vso[task.setvariable variable=tfVersion]$tfVersion"

  - task: TerraformInstaller@0
    displayName: 'install terraform $(tfVersion)'
    inputs:
      terraformVersion: $(tfVersion)

  - task: TerraformCLI@0
    displayName: Terraform init
    inputs:
      command: init
      terraformVersion: $(tfVersion)
      workingDirectory: $(System.DefaultWorkingDirectory)
      commandOptions: '-backend=false -input=false'
      # backendType: 'azurerm'
      # backendServiceArm: $(ServiceConnection)
      # backendAzureRmResourceGroupName: ${{ variables.resourceGroup }}
      # backendAzureRmStorageAccountName: ${{ variables.storageAccount }}
      # backendAzureRmContainerName: ${{ variables.container }}
      # backendAzureRmKey: 'pre/${{ lower(parameters.environment) }}/terraform.tfstate'

  - task: TerraformCLI@0
    displayName: Terraform validate
    inputs:
      command: 'validate'
      workingDirectory: $(System.DefaultWorkingDirectory)

  - task: TerraformCLI@0
    displayName: Terraform plan
    inputs:
      command: plan
      terraformVersion: $(tfVersion)
      commandOptions: '-out=tfplan -var-file=${{ parameters.environment }}.tfvars'
      workingDirectory: $(System.DefaultWorkingDirectory)
      environmentServiceNameAzureRM: $(ServiceConnection)

  # - stage: Precheck
  #   jobs:
  #     - job: Validate
  #       pool:
  #         vmImage: ${{ variables.agentPool }}
  #         timeoutInMinutes: ${{ variables.timeoutInMinutes }}
  #       steps:
  #         - task: TerraformInstaller@0
  #           displayName: Terraform install
  #           inputs:
  #             terraformVersion: ${{ variables.tfversion }}

  # - stage: Precheck
  #   jobs:
  #     - job:
  #       pool:
  #         vmImage: ${{ variables.agentPool }}
  #         timeoutInMinutes: ${{ variables.timeoutInMinutes }}
  #       steps:
  #         - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
  #           parameters:
  #             keyvaultName: 'infra-vault-nonprod'
  #             keyvaultSecret: 'azure-devops-token'
  #             serviceConnection: 'DCD-CFT-Sandbox'
  #             overrideAction: ${{ parameters.action }}

  # - task: TerraformCLI@0
  #   displayName: Terraform apply
  #   condition: and(succeeded(), eq('${{ parameters.Action }}', 'apply'))
  #   inputs:
  #     command: apply
  #     terraformVersion: $(tfVersion)
  #     commandOptions: '--auto-approve tfplan'
  #     workingDirectory: $(System.DefaultWorkingDirectory)
  #     environmentServiceNameAzureRM: 'devops-test-service-connection'
