name: Update Edit VM Run ID
on:
  schedule:
    - cron: "0 9 * * 1 " # Every Monday at 9:00 AM
  workflow_dispatch:

jobs:
  update_vm_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: master

      - name: Generate timestamp
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Generate day of the week
        run: echo "dow=$(date +'%u')" >> $GITHUB_ENV

      - name: Update variables.tf
        if: env.dow == 1 # Mondays only
        run: |
          awk -i inplace -v new_date="$date" '
            /variable "edit_vm_force_run_id" {/ {
            found=1
          }
            found && /default = "/ {
            sub(/[0-9]{8}/, new_date)
          }
            { print }
            ' variables.tf

      - name: Update variables.tf
        if: env.dow == 2 # Tuesdays only
        run: |
          awk -i inplace -v new_date="$date" '
            /edit_vm_force_run_id *= *"/ {
              sub(/[0-9]{8}/, new_date)
            }
            { print }
          ' prod.tfvars

      - name: Check for changes
        run: |
          if git diff --quiet variables.tf prod.tfvars; then
            echo "No changes detected. Exiting..."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected. Proceeding with commit."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PRE_APP_ID }}
          private-key: ${{ secrets.PRE_APP_PRIVATE_KEY }}

      - name: Commit and push changes
        if: env.changed == 'true'
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          echo "Committing and pushing changes..."
          git config --global user.name 'PRE DevOps'
          git config --global user.email '138598290+pre-devops@users.noreply.github.com'
          git add variables.tf prod.tfvars
          git commit -m "Update edit_vm_force_run_id to $date"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/hmcts/pre-shared-infrastructure.git
          git push origin master